<?php
/**
 * Plugin Name: Custom API Endpoint
 * Plugin URI:  https://github.com/example/custom-api-endpoint
 * Description: Alternative API endpoint that bypasses the /wp-json/ WordPress REST API path. Designed for InfinityFree and other restricted hosting environments that block the standard REST API at the firewall level.
 * Version:     1.0.0
 * Requires at least: 5.8
 * Requires PHP: 7.4
 * Author:      WordPress Pro
 * License:     GPL-2.0-or-later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: custom-api-endpoint
 *
 * @package CustomAPIEndpoint
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'CUSTOM_API_ENDPOINT_VERSION', '1.0.0' );
define( 'CUSTOM_API_ENDPOINT_DIR', plugin_dir_path( __FILE__ ) );
define( 'CUSTOM_API_ENDPOINT_FILE', __FILE__ );

require_once CUSTOM_API_ENDPOINT_DIR . 'includes/class-auth.php';
require_once CUSTOM_API_ENDPOINT_DIR . 'includes/class-data-provider.php';
require_once CUSTOM_API_ENDPOINT_DIR . 'includes/class-api-handler.php';
require_once CUSTOM_API_ENDPOINT_DIR . 'includes/class-admin.php';

register_activation_hook( __FILE__, 'custom_api_endpoint_activate' );
register_deactivation_hook( __FILE__, 'custom_api_endpoint_deactivate' );

/**
 * Plugin activation: write the endpoint script to WordPress root.
 */
function custom_api_endpoint_activate(): void {
	custom_api_endpoint_write_endpoint_file();
}

/**
 * Plugin deactivation: remove the endpoint script from WordPress root.
 */
function custom_api_endpoint_deactivate(): void {
	$endpoint_path = ABSPATH . 'wp-api-proxy.php';
	if ( file_exists( $endpoint_path ) ) {
		wp_delete_file( $endpoint_path );
	}
}

/**
 * Write (or overwrite) the endpoint script at the WordPress root.
 *
 * This standalone PHP file lives outside /wp-json/ and uses
 * include_once('wp-load.php') to bootstrap WordPress, bypassing
 * the InfinityFree firewall block on the REST API path.
 */
function custom_api_endpoint_write_endpoint_file(): void {
	$endpoint_path = ABSPATH . 'wp-api-proxy.php';

	$template = '<?php' . "\n"
		. '/**' . "\n"
		. ' * WordPress API Proxy Endpoint' . "\n"
		. ' *' . "\n"
		. ' * This file bypasses InfinityFree\'s /wp-json/ firewall block' . "\n"
		. ' * by serving API responses from the WordPress root directory.' . "\n"
		. ' *' . "\n"
		. ' * Generated by: Custom API Endpoint plugin' . "\n"
		. ' * @since 1.0.0' . "\n"
		. ' */' . "\n\n"
		. "define( 'CUSTOM_API_ENDPOINT_REQUEST', true );\n\n"
		. "\$wp_load = __DIR__ . '/wp-load.php';\n"
		. "if ( ! file_exists( \$wp_load ) ) {\n"
		. "    http_response_code( 500 );\n"
		. "    header( 'Content-Type: application/json' );\n"
		. "    echo wp_json_encode( array( 'error' => 'WordPress core not found.' ) );\n"
		. "    exit;\n"
		. "}\n\n"
		. "require_once \$wp_load;\n\n"
		. "// Ensure the plugin is active and handler class exists\n"
		. "\$handler_file = WP_PLUGIN_DIR . '/custom-api-endpoint/includes/class-api-handler.php';\n"
		. "if ( ! file_exists( \$handler_file ) || ! class_exists( 'Custom_API_Handler' ) ) {\n"
		. "    http_response_code( 500 );\n"
		. "    header( 'Content-Type: application/json' );\n"
		. "    echo wp_json_encode( array( 'error' => 'Custom API Endpoint plugin not active or not found.' ) );\n"
		. "    exit;\n"
		. "}\n\n"
		. "\$api = new Custom_API_Handler();\n"
		. "\$api->handle_request();\n";

	if ( is_writable( ABSPATH ) || is_writable( $endpoint_path ) ) {
		file_put_contents( $endpoint_path, $template, LOCK_EX );
	}
}

/**
 * Initialize admin interface.
 */
function custom_api_endpoint_init_admin(): void {
	new Custom_API_Admin();
}
add_action( 'init', 'custom_api_endpoint_init_admin' );

/**
 * Regenerate the endpoint file if it's missing (e.g., restored from backup
 * without the plugin directory, or manually deleted).
 */
function custom_api_endpoint_check_endpoint_file(): void {
	if ( is_admin() && current_user_can( 'manage_options' ) ) {
		$endpoint_path = ABSPATH . 'wp-api-proxy.php';
		if ( ! file_exists( $endpoint_path ) ) {
			custom_api_endpoint_write_endpoint_file();
		}
	}
}
add_action( 'admin_init', 'custom_api_endpoint_check_endpoint_file' );
